spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL:10.0.0.134:3306/subway}?allowMultiQueries=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:masterpw}
