spring:
  profiles:
    active: local
security:
  jwt:
    token:
      expire-length: '3600000'
      secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno
handlebars:
  suffix: .html
  enabled: 'true'


