spring:
  datasource:
    url: jdbc:mysql://192.168.66.154:3306/subway?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: masterpw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
