version: '3'
services:
  local-db:
    image: brainbackdoor/data-subway:0.0.1
    container_name: local-db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: masterpw
      MYSQL_DATABASE: subway
      MYSQL_USER: root
      MYSQL_PASSWORD: masterpw
      TZ: Asia/Seoul